In [1]:
# Import Libraries

In [10]:
import pandas as pd
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [12]:
df=pd.read_csv('/Users/ildem/Downloads/movie_metadata.csv')

In [13]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

### 2. Use crosstabs to show the number of moovies per country

In [26]:
pd.crosstab(df.country, df.genres, margins=True).All

country
Afghanistan                1
Argentina                  4
Aruba                      1
Australia                 55
Bahamas                    1
                        ...
UK                       448
USA                     3807
United Arab Emirates       1
West Germany               3
All                     5038
Name: All, Length: 66, dtype: int64

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [21]:
pd.crosstab(df.country, [df.director_name, df.genres])

director_name                                 A. Raven Cruz  \
genres               Action|Adventure|Comedy|Fantasy|Sci-Fi
country
Afghanistan                                               0
Argentina                                                 0
Aruba                                                     0
Australia                                                 0
Bahamas                                                   0
...                                                     ...
Turkey                                                    0
UK                                                        0
USA                                                       1
United Arab Emirates                                      0
West Germany                                              0

director_name                                  Aaron Hann Aaron Schneider  \
genres               Drama|Horror|Mystery|Sci-Fi|Thriller   Drama|Mystery
country
Afghanistan                                             0               0
Argentina                                               0               0
Aruba                                                   0               0
Australia                                               0               0
Bahamas                                                 0               0
...                                                   ...             ...
Turkey                                                  0               0
UK                                                      0               0
USA                                                     1               1
United Arab Emirates                                    0               0
West Germany                                            0               0

director_name         Aaron Seltzer Abel Ferrara          Adam Brooks  \
genres               Comedy|Romance  Crime|Drama Comedy|Drama|Romance
country
Afghanistan                       0            0                    0
Argentina                         0            0                    0
Aruba                             0            0                    0
Australia                         0            0                    0
Bahamas                           0            0                    0
...                             ...          ...                  ...
Turkey                            0            0                    0
UK                                0            0                    0
USA                               1            1                    0
United Arab Emirates              0            0                    0
West Germany                      0            0                    0

director_name        Adam Carolla Adam Goldberg    Adam Green  \
genres                     Comedy Drama|Mystery Comedy|Horror
country
Afghanistan                     0             0             0
Argentina                       0             0             0
Aruba                           0             0             0
Australia                       0             0             0
Bahamas                         0             0             0
...                           ...           ...           ...
Turkey                          0             0             0
UK                              0             0             0
USA                             1             1             1
United Arab Emirates            0             0             0
West Germany                    0             0             0

director_name        Adam Jay Epstein  ... Zack Ward Zackary Adler  \
genres                         Comedy  ...    Horror   Crime|Drama
country                                ...
Afghanistan                         0  ...         0             0
Argentina                           0  ...         0             0
Aruba                               0  ...         0             0
Australia                           0  ...         0             0
Bahamas                             0  ...         0             0
...                               ...  ...       ...           ...
Turkey                              0  ...         0             0
UK                                  0  ...         0             1
USA                                 1  ...         1             0
United Arab Emirates                0  ...         0             0
West Germany                        0  ...         0             0

director_name                       Zak Penn                Zal Batmanglij  \
genres               Adventure|Comedy|Horror Drama|Mystery|Sci-Fi|Thriller
country
Afghanistan                                0                             0
Argentina                                  0                             0
Aruba                                      0                             0
Australia                                  0                             0
Bahamas                                    0                             0
...                                      ...                           ...
Turkey                                     0                             0
UK                                         1                             0
USA                                        0                             1
United Arab Emirates                       0                             0
West Germany                               0                             0

director_name                              Zoran Lisinac  \
genres               Drama|Thriller Comedy|Music|Romance
country
Afghanistan                       0                    0
Argentina                         0                    0
Aruba                             0                    0
Australia                         0                    0
Bahamas                           0                    0
...                             ...                  ...
Turkey                            0                    0
UK                                1                    0
USA                               0                    1
United Arab Emirates              0                    0
West Germany                      0                    0

director_name            Álex de la Iglesia Émile Gaudreault  \
genres               Crime|Mystery|Thriller     Comedy|Drama
country
Afghanistan                               0                0
Argentina                                 0                0
Aruba                                     0                0
Australia                                 0                0
Bahamas                                   0                0
...                                     ...              ...
Turkey                                    0                0
UK                                        0                0
USA                                       0                0
United Arab Emirates                      0                0
West Germany                              0                0

director_name                        Éric Tessier         Étienne Faure
genres               Action|Drama|Horror|Thriller Drama|Musical|Romance
country
Afghanistan                                     0                     0
Argentina                                       0                     0
Aruba                                           0                     0
Australia                                       0                     0
Bahamas                                         0                     0
...                                           ...                   ...
Turkey                                          0                     0
UK                                              0                     0
USA                                             0                     0
United Arab Emirates                            0                     0
West Germany                                    0                     0

[65 rows x 4461 columns]

### 4. Average duration of filmes grouped by color

In [46]:
pd.crosstab(df.color, df.duration, values=df.duration, aggfunc='mean', margins=True).All

color
 Black and White    112.253589
Color               107.042908
All                 107.260279
Name: All, dtype: float64

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [44]:
df['Total_likes']=df.actor_1_facebook_likes + df.actor_2_facebook_likes + df.actor_3_facebook_likes

pd.crosstab(df.director_name, df.Total_likes, values=df.Total_likes, aggfunc='mean', margins=True).All

director_name
A. Raven Cruz          1094.000000
Aaron Hann              406.000000
Aaron Schneider       16970.000000
Aaron Seltzer          4598.000000
Abel Ferrara           2198.000000
                          ...
Álex de la Iglesia      702.000000
Émile Gaudreault        917.000000
Éric Tessier             72.000000
Étienne Faure            19.000000
All                    9012.978857
Name: All, Length: 2386, dtype: float64